apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms-deployment
spec:
  selector:
    matchLabels:
      app: kms
  replicas: 1
  template:
    metadata:
      labels:
        app: kms
    spec:
      containers:
      - name: kms
        image: whfuyn/kms_standalone:adapt-v0.1.0
        command: ["kms", "run", "config/config.toml"]
        workingDir: /kms_standalone
        ports:
        - containerPort: 55555
        volumeMounts:
        - name: kms-config
          mountPath: /kms_standalone/config
      volumes:
      - name: kms-config
        secret:
          secretName: kms-config
          items:
          - key: config.toml
            path: config.toml
