apiVersion: v1
kind: Service
metadata:
  name: kms-standalone
  labels:
    run: kms-standalone
spec:
  ports:
  - port: 55555
  selector:
    app: kms-standalone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms-standalone
spec:
  selector:
    matchLabels:
      app: kms-standalone
  replicas: 1
  template:
    metadata:
      labels:
        app: kms-standalone
    spec:
      containers:
      - name: kms-standalone
        image: whfuyn/kms_standalone:adapt-v0.1.0
        command: ["kms", "run", "config/config.toml"]
        workingDir: /kms_standalone
        ports:
        - containerPort: 55555
        volumeMounts:
        - name: kms-standalone-config
          mountPath: /kms_standalone/config
      volumes:
      - name: kms-standalone-config
        secret:
          secretName: kms-standalone-config
          items:
          - key: config.toml
            path: config.toml
