apiVersion: v1
kind: Secret
metadata:
  name: kms-config
type: Opaque
stringData:
  # TODO:
  # It's better to extract config entries to ConfigMap.
  # Only db_url and master_password needs to use Secret.
  # But that will make the kms service harder to load.
  config.toml: |
    [kms_standalone]
    grpc_listen_port = 55555

    db_url = "mysql://root:pwd@mysql:3306/kms-standalone"
    master_password = "00000000000000000000000000" # 请自行配置主密码

    db_conn_timeout_millis = 10000  # 10 seconds
    db_conn_idle_timeout_millis = 20000 # 20 seconds
    db_max_connections = 16

